
domain: g14n.info

gems:
  - jekyll-sitemap

markdown: kramdown

collections:
  examples:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: common/page

# Custom vars

google-analytics:
  id: UA-12635045-12

