
domain: g14n.info

gems:
  - jekyll-sitemap

markdown: kramdown

nav:
  Home: //g14n.info/tris3d-canvas
  Example: //g14n.info/tris3d-canvas/example/
  Code: https://github.com/fibo/tris3d-canvas

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: common/page

