
domain: g14n.info

gems:
  - jekyll-sitemap

markdown: kramdown

nav:
  Example: //g14n.info/tris3d-canvas/example/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: common/page

